# Generated by Django 4.0.6 on 2022-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='user name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(null=True, verbose_name='date of birth')),
                ('is_active', models.BooleanField(default=True, verbose_name='is user active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is user admin')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='last name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
